### ISSUE TITLE
Compression options

### ISSUE THREAD

**Issue by meggart** [jhamman/xpublish#20]
Thanks for the very nice package. I wanted to ask if it is possible to control the compression used by the server side to represent the chunks. For me the compressor is always set to Blosc with compression level 5, is there a way to customize this?

**Comment by jhamman** [comment]
Yes! You can do this already by setting the encoding of individual variables:

```python
    from numcodecs import Zstd


    for k, da in ds.variables.items():
        # to turn off compression:
        da.encoding['compressor'] = None
        # or to set compression to something other than the default:
        da.encoding['compressor'] = Zstd(level=1)
```

**Comment by meggart** [comment]
Great, thanks for the hint, that does the trick.
