### ISSUE TITLE
Server-side caching

### ISSUE THREAD

**Issue by jhamman** [jhamman/xpublish#9]
We may want to look into adding a server-side cache of some kind. We probably want to make this work with dask and dask-distributed for keys explicitly computed, e.g.:

https://github.com/jhamman/xpublish/blob/36befed89d880b8d249b1c587dd994e40a3e76a0/xpublish/rest.py#L299-L300

I know dask has some experimental caching functionality (https://docs.dask.org/en/latest/caching.html) as well as an old companion project [cachey](https://github.com/dask/cachey). It is possible we don't really need anything since dask's caching could be turned on by the data publisher:

```python

import xarray as xr
import xpublish
from dask.cache import Cache

cache = Cache(2e9)  # Leverage two gigabytes of memory
cache.register()    # Turn cache on globally

ds = xr.open_mfdataset(...)
...
ds.rest.serve()

```

I'm also curious how dask's caching functionality works with distributed.

**Comment by andersy005** [comment]
During today's dask dev meeting, I asked a question about the status of this experimental caching functionality. It turns out that this only works for single node cluster, i.e. won't work when using distributed.
